#!/bin/bash
set -e

REPO_RAW="${REPO_RAW:-https://raw.githubusercontent.com/vhqtvn/vh-tricks/main}"
BASE="$REPO_RAW/claude/multi/files"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/claude-multi"

: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${XDG_DATA_HOME:=$HOME/.local/share}"
CONFIG_DIR="$XDG_CONFIG_HOME/claude-multi"
CONFIG_FILE="$CONFIG_DIR/config"
MARKER_BEGIN="# >>> vh-tricks: claude/multi >>>"
MARKER_END="# <<< vh-tricks: claude/multi <<<"

remove_rc_block() {
  for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    [ -f "$rc" ] || continue
    sed -i "\|$MARKER_BEGIN|,\|$MARKER_END|d" "$rc"
  done
}

# --- Load persisted config so updates / reinstalls reuse prior settings ----
# Snapshot env-provided overrides FIRST so they win even over an old-format
# (hard-assign) config left by an earlier version.
CM_VARS="ROOT PROFILES SHARED CACHE WRITABLE RUNTIME_DIR LINK_MAIN"
for _v in $CM_VARS; do
  eval "_envset_$_v=\${CLAUDE_MULTI_$_v+set}"
  eval "_envval_$_v=\${CLAUDE_MULTI_$_v-}"
done
if [ -f "$CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  . "$CONFIG_FILE"
fi
# Re-apply any override that was present in the environment.
for _v in $CM_VARS; do
  if [ "$(eval echo "\${_envset_$_v}")" = set ]; then
    eval "CLAUDE_MULTI_$_v=\${_envval_$_v}"
  fi
done
: "${CLAUDE_MULTI_ROOT:=$XDG_DATA_HOME/claude-multi}"

list_profile_wrappers() {
  # Print wrapper paths for the currently-configured profiles.
  for prof in ${CLAUDE_MULTI_PROFILES:-}; do
    echo "$BIN_DIR/claude-$prof"
  done
}

# --------------------------------- Uninstall -------------------------------
if [ "$1" = "--uninstall" ] || [ "$1" = "--purge" ]; then
  rm -f "$LAUNCHER"
  for w in $(list_profile_wrappers); do rm -f "$w"; done
  remove_rc_block
  if [ "$1" = "--purge" ]; then
    rm -rf "${CLAUDE_MULTI_ROOT:-$XDG_DATA_HOME/claude-multi}"
    rm -rf "$CONFIG_DIR"
    echo "Purged claude/multi: binaries, config, and ALL profile/shared state removed."
  else
    echo "Uninstalled claude/multi binaries + PATH entry."
    echo "Kept state ($CLAUDE_MULTI_ROOT) and config ($CONFIG_FILE) for reinstall."
    echo "To remove everything: re-run with --purge"
  fi
  exit 0
fi

# ------------------------------- Requirements ------------------------------
if ! command -v bwrap >/dev/null 2>&1; then
  echo "bubblewrap (bwrap) is required. Install it first, e.g.:"
  echo "  arch:   sudo pacman -S bubblewrap"
  echo "  debian: sudo apt install bubblewrap"
  exit 1
fi

# ------------------------- Resolve settings (env > config > default) --------
# Space-separated list of profiles to create wrappers for.
CLAUDE_MULTI_PROFILES="${CLAUDE_MULTI_PROFILES:-a b}"
CLAUDE_MULTI_ROOT="${CLAUDE_MULTI_ROOT:-$XDG_DATA_HOME/claude-multi}"
CLAUDE_MULTI_SHARED="${CLAUDE_MULTI_SHARED:-projects}"
CLAUDE_MULTI_CACHE="${CLAUDE_MULTI_CACHE:-1}"
CLAUDE_MULTI_WRITABLE="${CLAUDE_MULTI_WRITABLE:-}"
CLAUDE_MULTI_RUNTIME_DIR="${CLAUDE_MULTI_RUNTIME_DIR:-1}"
# Shared subdirs to symlink to the main (non-sandboxed) ~/.claude at setup:
# a space list of names, or "all" for the whole shared set, or "" to skip.
CLAUDE_MULTI_LINK_MAIN="${CLAUDE_MULTI_LINK_MAIN:-}"

# ------------------------------- Persist config ----------------------------
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true
cat > "$CONFIG_FILE" <<EOF
# claude/multi configuration (generated by install.sh; safe to edit).
# Reused on update and reinstall. Override at install time with env vars,
# or run the installer with --purge to reset everything.
#
# Values use ":= default" so an environment variable, if set, OVERRIDES the
# stored value both here and in the launcher (e.g. CLAUDE_MULTI_SHARED=... claude-a).
: "\${CLAUDE_MULTI_ROOT:=$CLAUDE_MULTI_ROOT}"
: "\${CLAUDE_MULTI_PROFILES:=$CLAUDE_MULTI_PROFILES}"
: "\${CLAUDE_MULTI_SHARED:=$CLAUDE_MULTI_SHARED}"
: "\${CLAUDE_MULTI_CACHE:=$CLAUDE_MULTI_CACHE}"
: "\${CLAUDE_MULTI_WRITABLE:=$CLAUDE_MULTI_WRITABLE}"
: "\${CLAUDE_MULTI_RUNTIME_DIR:=$CLAUDE_MULTI_RUNTIME_DIR}"
: "\${CLAUDE_MULTI_LINK_MAIN:=$CLAUDE_MULTI_LINK_MAIN}"
EOF
chmod 600 "$CONFIG_FILE" 2>/dev/null || true

# ------------------------------- Install launcher --------------------------
mkdir -p "$BIN_DIR"
if [ -f "./files/claude-multi" ]; then
  cp "./files/claude-multi" "$LAUNCHER"   # local run from a cloned repo
else
  curl -fsSL "$BASE/claude-multi" -o "$LAUNCHER"
fi
chmod +x "$LAUNCHER"

# ------------------------- Generate per-profile wrappers -------------------
# Remove wrappers for profiles no longer configured is left to --purge; here
# we just (re)create wrappers for the configured set.
for prof in $CLAUDE_MULTI_PROFILES; do
  case "$prof" in ''|*[!A-Za-z0-9_.-]*) echo "skip invalid profile name: '$prof'"; continue ;; esac
  wrapper="$BIN_DIR/claude-$prof"
  cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# vh-tricks claude/multi — launch Claude Code as profile '$prof'
exec "$LAUNCHER" run "$prof" "\$@"
EOF
  chmod +x "$wrapper"
  echo "Wrapper: $wrapper"
done

# ------------------------------- Init state --------------------------------
export CLAUDE_MULTI_ROOT CLAUDE_MULTI_SHARED CLAUDE_MULTI_CACHE
for prof in $CLAUDE_MULTI_PROFILES; do
  case "$prof" in ''|*[!A-Za-z0-9_.-]*) continue ;; esac
  "$LAUNCHER" init "$prof" >/dev/null || true
done

# Optionally share selected subdirs with the main (non-sandboxed) ~/.claude.
# link-main checks + confirms every removal itself (prompting on /dev/tty, which
# works under `curl ... | bash`); set CLAUDE_MULTI_YES=1 to auto-confirm.
if [ -n "$CLAUDE_MULTI_LINK_MAIN" ]; then
  echo
  echo "Setting up main-share (CLAUDE_MULTI_LINK_MAIN=\"$CLAUDE_MULTI_LINK_MAIN\")..."
  case "$CLAUDE_MULTI_LINK_MAIN" in
    all|1|yes|true) "$LAUNCHER" link-main --all ;;
    *)              "$LAUNCHER" link-main $CLAUDE_MULTI_LINK_MAIN ;;
  esac || echo "  (main-share skipped/aborted; run 'claude-multi link-main' later)"
fi

# ------------------------------- PATH on rc --------------------------------
remove_rc_block
PATH_BLOCK="$MARKER_BEGIN
export PATH=\"\$HOME/.local/bin:\$PATH\"
$MARKER_END"
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  [ -f "$rc" ] || continue
  case ":$PATH:" in *":$BIN_DIR:"*) ;; *) echo "$PATH_BLOCK" >> "$rc" ;; esac
done

echo
echo "Done! claude/multi installed."
echo "  Root:     $CLAUDE_MULTI_ROOT"
echo "  Shared:   $CLAUDE_MULTI_SHARED"
echo "  Profiles: $CLAUDE_MULTI_PROFILES"
echo
echo "Next:"
echo "  1. Restart your shell (or: export PATH=\"\$HOME/.local/bin:\$PATH\")"
echo "  2. (optional) seed first profile from your current login:"
echo "       claude-multi import ${CLAUDE_MULTI_PROFILES%% *} --seed-shared"
echo "  3. Log each profile in:   claude-a   then /login    (then claude-b ...)"
echo "  4. Verify isolation:      claude-multi verify"
echo
echo "Uninstall (keep state): curl ... | bash -s -- --uninstall"
echo "Full reset:             curl ... | bash -s -- --purge"
